
04. timezone 설정
   3) tzselect 
      5(Asia) => 23(Korea south)
   4) rdate -s time.bora.net
01. yum makecache fast
02. yum -y update
05. yum -y group install 'Development tools'
    yum -y install systemtap-sdt-devel

01. remi repository setup 
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm

02. remi-php74 repository activation
yum install yum-utils
yum-config-manager --enable remi-php74

yum --enablerepo=remi-php74 install  httpd httpd-devel \
php php-devel php-common php-cli \
php-redis \
php-brotli \
php-curl \
php-gd \
php-gmp \
php-imap \
php-bcmath \
php-json \
php-mbstring \
php-mysqlnd \
php-opcache \
php-tidy \
php-pdo \
php-pear \
php-process \
php-pecl-apcu \
php-pecl-geoip \
php-pecl-gmagick \
php-pecl-hrtime \
php-pecl-json \
php-pecl-mongodb \
php-pecl-zip \
php-xdebug \
php-xml
php-zip

  
07. /etc/profile edit
##################### oracle oci setting
export ORACLE_HOME=/usr/lib/oracle/18.5
export TNS_ADMIN=$ORACLE_HOME/NETWORK/admin
export LD_LIBRARY_PATH=$ORACLE_HOME:$ORACLE_HOME/sdk
export PATH=$PATH:$ORACLE_HOME:$ORACLE_HOME/bin
export PHP_DTRACE=yes

08. source /etc/profile
09. download oracle 18.5 instantclient  패키지 다운로드 / 설치
   https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html
   download instantclient-basic-linux.x64-version.zip
   download instantclient-sdk-linux.x64-version.zip
   download instantclient-sqlplus-linux.x64-version.zip <-- sqlplus 사용으로 필요, 사용치 않으면 필요없음   
   unzip *	
   mv instantclient_18_5/ /usr/lib/oracle/18.5
   mkdir -p /usr/lib/oracle/18.5/bin /usr/lib/oracle/18.5/doc /usr/lib/oracle/18.5/NETWORK/admin 
   ln -s libclntsh.so.18.1 libclntsh.so
   ln -s libocci.so.18.1 libocci.so
   cp libclntsh.so.* /lib64/
   cp libocci.so.* /lib64/
   mv adrci exp expdp genezi imp impdp sqlldr sqlplus uidrvci wrc bin 
   mv BASIC_README glogin.sql SQLPLUS_README TOOLS_README
   vi NETWORK/admin/sqlnet.ora
DIAG_ADR_ENABLED=off

TRACE_LEVEL_CLIENT=off
LOG_FILE_CLIENT=/dev/null

   vi NETWORK/admin/tnsnames.ora  
# tnsnames.ora Network Configuration File
# Generated by Oracle configuration tools.

ORCL =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = orcl)
    )
  )

서비스명 =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 아이피)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = 서비스명)
    )
  )

DIAG_ADR_ENABLED=off

10. echo /usr/lib/oracle/18.5 > /etc/ld.so.conf.d/oracle-instantclient
11. ldconfig
 
14. oracle oci8 설치 --  http://pecl.php.net/package/oci8
   wget http://pecl.php.net/get/oci8-2.2.0.tgz   
   cd oci8
   phpize
   ./configure --with-oci8=instantclient,/usr/lib/oracle/18.5,18.5
   make install
 
15. /etc/php.d/20-oci8.ini
; Enable oci8 extension module
extension=oci8

 
 
