
##############################################################################
###### 아마존 리눅스에 APACHE + PHP + ORACLE 설치
##############################################################################
01. yum makecache fast
02. yum -y update
03. yum -y install rdate htop mc nmap fail2ban rec2
04. timezone 설정
   1) /etc/sysconfig/clock 수정
      ZONE = "Asia/Seoul"
      UTC=false
   2) mv /etc/localtime /etc/localtime.UTC
      cp -p /usr/share/zoneinfo/Asia/Seoul /etc/localtime
   3) tzselect 
      5(Asia) => 23(Korea south)
   4) rdate -s time.bora.net
05. yum -y group install 'Development tools'
06. yum -y install httpd24* php71* 
07. /etc/profile edit
##################### oracle oci setting
export ORACLE_HOME=/usr/lib/oracle/12.2
export TNS_ADMIN=$ORACLE_HOME/NETWORK/admin
export LD_LIBRARY_PATH=$ORACLE_HOME:$ORACLE_HOME/sdk
export PATH=$PATH:$ORACLE_HOME:$ORACLE_HOME/bin

##################### nodejs setting
export NODEJS_HOME=/web/nodejs6
export PATH=$PATH:$NODEJS_HOME/bin
08. source /etc/profile
09. download oracle 12c instantclient  패키지 다운로드 / 설치
   http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html
   download instantclient-basic-linux.x64-version.zip
   download instantclient-sdk-linux.x64-version.zip
   download instantclient-sqlplus-linux.x64-version.zip <-- sqlplus 사용으로 필요, 사용치 않으면 필요없음   
   unzip *	
   mv instantclient_12_2/ /usr/lib/oracle/12.2
   mkdir -p /usr/lib/oracle/12.2/bin /usr/lib/oracle/12.2/doc /usr/lib/oracle/12.2/NETWORK/admin 
   ln -s libclntsh.so.12.1 libclntsh.so
   ln -s libocci.so.12.1 libocci.so
   mv adrci exp expdp genezi imp impdp sqlldr sqlplus uidrvci wrc bin 
   mv BASIC_README glogin.sql SQLPLUS_README TOOLS_README
   vi NETWORK/admin/sqlnet.ora
DIAG_ADR_ENABLED=off

TRACE_LEVEL_CLIENT=off
LOG_FILE_CLIENT=/dev/null

   vi NETWORK/admin/tnsnames.ora  
# tnsnames.ora Network Configuration File
# Generated by Oracle configuration tools.

ORCL =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = orcl)
    )
  )

서비스명 =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 아이피)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = 서비스명)
    )
  )


10. echo /usr/lib/oracle/12.2 > /etc/ld.so.conf.d/oracle-instantclient
11. ldconfig
12. oracle 접속 확인
	# sqlplus 아이디/비밀번호@//아이피:포트/서비스명  
  # sqlplus 아이디/비밀번호@서비스명
13. php7.1 down
   wget http://jp2.php.net/get/php-7.1.17.tar.gz/from/this/mirror -O php-7.1.17.tar.gz
   tar xvzf php-7.1.17.tar.gz
   cd php-7.1.17/ext/
14. oracle oci8 설치
   cd oci8
   phpize
   ./configure --with-oci8=instantclient,/usr/lib/oracle/12.2,12.2
   make install
15. oracle pdo_oci 설치 - 현재 에러 발생 (해결 방법 찾지 못함)   
   오류내용 : undefined symbol: php_pdo_unregister_driver
   cd pdo_oci
   phpize
   ./configure --with-pdo-oci=instantclient,/usr/lib/oracle/12.2,12.2.0.1.0
   make install
16. php.ini 설정 (오라클포함)
    extension=oci8.so
    extension=pdo_oci.so -- 에러발생시(제외시킴)
    short_tag = On
    timezone = Asia/Seoul
    display_errors = On
 17. composer install (설치가 안되어 있다면)
   curl -sS https://getcomposer.org/installer | /usr/bin/php && mv composer.phar /usr/bin/composer


##############################################################################
###### 아마존 Zadara(NAS) 설치
##############################################################################
1. Zadara 설치 - 자동
    wget -O ~/vpsa_linux.sh "https://172.28.212.100/api/servers/vpsa_linux.sh?iscsi=yes&fc=no&vpsachapuser=$vpsachapuser&vpsachapsecret=$vpsachapsecret&access_key=$access_key" --no-check-certificate
    sudo yum -y install iscsi-initiator-utils.x86_64
    mount -t nfs 172.28.212.100:/export/폴더명 폴더명 

1. Zadara 설치 - 수동 (zadara GUI사이트에서 설정후)
    mount -t nfs 172.28.212.100:/export/폴더명 폴더명  
